export const tutorial = [
    {id: 1, title: 'Introduction', 
    content: ['An introduction to database foundations', 
    'What you should know',
]},
    {id: 2, title: 'Database Core Concepts', content: ['What is a database?', 
    'Storing data efficiently', 'Relational database management systems'
]},
    {id: 3, title: 'Set up a Database Playground', content: ['An introduction to database foundations', 
    'What you should know',
]},
    {id: 4, title: 'Graphical Interfaces', content: ['An introduction to database foundations', 
    'What you should know',
]},
    {id: 5, title: 'Create a Table Objects', content: ['An introduction to database foundations', 
    'What you should know',
]},
    {id: 6, title: 'Add Data to a Table', content: ['An introduction to database foundations', 
    'What you should know',
]},
    {id: 7, title: 'Retrieve Information', content: ['An introduction to database foundations', 
    'What you should know',
]},
    {id: 8, title: 'Manipulate Data', content: ['An introduction to database foundations', 
    'What you should know',
]},
    {id: 9, title: 'Conclusion', content: ['An introduction to database foundations', 
    'What you should know',
]},
]