export const coursesCard = [
  {
    id: 1,
    topic: "basic",
    coursesName: "Database Foundations: Intro to Databases",
    name: "by Adam Wilbert",
    length: "3h 21m",
  },
  {
    id: 2,
    topic: "basic",
    coursesName: "Database Foundations: Data Structures",
    name: "by Sunil Bishowkaram",
    length: "2h 55m",
  },
  {
    id: 3,
    topic: "basic",
    coursesName: "Database Foundations: Database Management",
    name: "by Adam Wilbert",
    length: "2h 14m",
  },
  {
    id: 4,
    topic: "basic",
    coursesName: "Database Foundations: Administration",
    name: "by Emma Saunders",
    length: "2h 7m",
  },
  {
    id: 5,
    topic: "basic",
    coursesName: "Database Foundations: Application Development",
    name: "by Adam Wilbert",
    length: "1h 49m",
  },
  {
    id: 6,
    topic: "relational",
    coursesName: "Learning Relational Databases",
    name: "by Sunil Bishowkaram",
    length: "5h 50m",
  },
  {
    id: 7,
    topic: "relational",
    coursesName: "Relational Databases Essential Training",
    name: "by Sunil Bishowkaram",
    length: "5h 15m",
  },
  {
    id: 8,
    topic: "relational",
    coursesName: "Finding New Career Paths with SQL ",
    name: "by Sunil Bishowkaram",
    length: "2h 15m",
  },
  {
    id: 9,
    topic: "relational",
    coursesName: "Relational database concepts",
    name: "by Sunil Bishowkaram",
    length: "5h 4m",
  },
  {
    id: 10,
    topic: "sql",
    coursesName: "SQL Essential Training",
    name: "by Bill Weinman",
    length: "5h 4m",
  },
  {
    id: 11,
    topic: "sql",
    coursesName: "SQL for Data Analysis",
    name: "by Sunil Bishowkaram",
    length: "5h 4m",
  },
  {
    id: 12,
    topic: "sql",
    coursesName: "SQL: Data Reporting and Analysis",
    name: "by Emma Saunders",
    length: "5h 4m",
  },
  {
    id: 13,
    topic: "sql",
    coursesName: "SQL for Non-Programmers",
    name: "by Julianne Thouin",
    length: "5h 4m",
  },
  {
    id: 14,
    topic: "sql",
    coursesName: "Quick Start Guide to SQL",
    name: "by Deepa Maddala",
    length: "5h 4m",
  },
  {
    id: 15,
    topic: "sql",
    coursesName: "Intermediate SQL for Data Scientists",
    name: "by Dan Sullivan",
    length: "5h 4m",
  },
];
