export const coursesCard = [
  {
    id: 1,
    topic: "basic_concepts",
    coursesName: "Database Foundations: Intro to Databases",
    name: "by Adam Wilbert",
    totalTime: "50 lectures (3h 21m)",
  },
  {
    id: 2,
    topic: "basic_concepts",
    coursesName: "Database Foundations: Data Structures",
    name: "by Adam Wilbert",
    totalTime: "30 lectures (2h 55m)",
  },
  {
    id: 3,
    topic: "basic_concepts",
    coursesName: "Database Foundations: Database Management",
    name: "by Adam Wilbert",
    totalTime: "50 lectures (2h 14m)",
  },
  {
    id: 4,
    topic: "sql_queries",
    coursesName: "Database Foundations: Administration",
    name: "by Adam Wilbert",
    totalTime: "20 lectures (2h 7m)",
  },
  {
    id: 5,
    topic: "sql_queries",
    coursesName: "Database Foundations: Application Development",
    name: "by Adam Wilbert",
    totalTime: "100 lectures (1h 49m)",
  },
  {
    id: 6,
    topic: "sql_queries",
    coursesName: "Learn Frontend Programming Language",
    name: "by Sunil Bishowkaram",
    totalTime: "200 lectures (300 hrs)",
  },
  {
    id: 7,
    topic: "NoSQL",
    coursesName: "Introducing to with HTML / CSS",
    name: "by Price",
    totalTime: "20 lectures (50 hrs)",
  },
  {
    id: 8,
    topic: "NoSQL",
    coursesName: "Introducing to with JAVA",
    name: "by Petter",
    totalTime: "80 lectures (200 hrs)",
  },
  {
    id: 9,
    topic: "NoSQL",
    coursesName: "Introducing to with HTML / CSS / JAVASCRIPT",
    name: "by Petter",
    totalTime: "50 lectures (50 hrs)",
  },
];
