export const coursesCard = [
  {
    id: 1,
    topic: "basic",
    coursesName: "Database Foundations: Intro to Databases",
    name: "by Adam Wilbert",
    length: "3h 21m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Data Types'},
      {id: 3, title: 'Design a Normalized Databases'},
      {id: 4, title: 'Identify Rows with Primary Keys'},
      {id: 5, title: 'Formalize Data Relationships'},
      {id: 6, title: 'Indexes'},
      {id: 7, title: 'Constraints'},
      {id: 8, title: 'Conclusion'}]},
  {
    id: 2,
    topic: "basic",
    coursesName: "Database Foundations: Data Structures",
    name: "by Sunil Bishowkaram",
    length: "2h 55m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 3,
    topic: "basic",
    coursesName: "Database Foundations: Database Management",
    name: "by Adam Wilbert",
    length: "2h 14m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Views'},
      {id: 3, title: 'Query Performance'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 4,
    topic: "basic",
    coursesName: "Database Foundations: Administration",
    name: "by Emma Saunders",
    length: "2h 7m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 5,
    topic: "basic",
    coursesName: "Database Foundations: Application Development",
    name: "by Adam Wilbert",
    length: "1h 49m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 6,
    topic: "relational",
    coursesName: "Learning Relational Databases",
    name: "by Sunil Bishowkaram",
    length: "5h 50m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 7,
    topic: "relational",
    coursesName: "Relational Databases Essential Training",
    name: "by Sunil Bishowkaram",
    length: "5h 15m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 8,
    topic: "relational",
    coursesName: "Finding New Career Paths with SQL ",
    name: "by Sunil Bishowkaram",
    length: "2h 15m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 9,
    topic: "relational",
    coursesName: "Relational database concepts",
    name: "by Sunil Bishowkaram",
    length: "5h 4m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    _id: 10,
    topic: "sql",
    coursesName: "SQL Essential Training",
    name: "by Bill Weinman",
    length: "5h 4m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    _id: 11,
    topic: "sql",
    coursesName: "SQL for Data Analysis",
    name: "by Sunil Bishowkaram",
    length: "5h 4m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 12,
    topic: "sql",
    coursesName: "SQL: Data Reporting and Analysis",
    name: "by Emma Saunders",
    length: "5h 4m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 13,
    topic: "sql",
    coursesName: "SQL for Non-Programmers",
    name: "by Julianne Thouin",
    length: "5h 4m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 14,
    topic: "sql",
    coursesName: "Quick Start Guide to SQL",
    name: "by Deepa Maddala",
    length: "5h 4m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
  {
    id: 15,
    topic: "sql",
    coursesName: "Intermediate SQL for Data Scientists",
    name: "by Dan Sullivan",
    length: "5h 4m",
    tutorial: [
      {id: 1, title: 'Introduction'},
      {id: 2, title: 'Database Core Concepts'},
      {id: 3, title: 'Set up a Database Playground'},
      {id: 4, title: 'Graphical Interfaces'},
      {id: 5, title: 'Create a Table Objects'},
      {id: 6, title: 'Add Data to a Table'},
      {id: 7, title: 'Retrieve Information'},
      {id: 8, title: 'Manipulate Data'},
      {id: 9, title: 'Conclusion'}]
  },
];
